name: HIVE-SNAP
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Setup Snapcraft
      run: |
        sudo snap install snapcraft --classic
        echo "$SNAP_TOKEN" | snapcraft login --with -
        snapcraft
        snapcraft upload --release=stable *.snap
      env:
        SNAP_TOKEN: ${{secrets.SNAP_TOKEN}}
        SNAPCRAFT_BUILD_ENVIRONMENT: host